import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import QueryProvider from '@/client/QueryProvider';
import { HydrationBoundary, QueryClient, dehydrate } from '@tanstack/react-query';
import { getData } from '@/server/actions/getData';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const queryClient = new QueryClient();

  await queryClient.prefetchQuery({
    queryKey: ['animes', ''],
    queryFn: getData,
  });

  return (
    <html lang="en">
      <body className={inter.className}>
        <QueryProvider>
          <HydrationBoundary state={dehydrate(queryClient)}>{children}</HydrationBoundary>
        </QueryProvider>
      </body>
    </html>
  );
}
